services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/backend
    ports:
      - 8080:8080
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      PORT: 8080
      DATABASE_URL: postgres://postgres:root@postgres:5432/expenses
      FIXER_KEY: FIXER_KEY

  postgres:
    build: ./docker/db
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: expenses
